[workspace]
members = [
    'pallet-ajuna-matchmaker',
    'pallet-ajuna-gameregistry',
    'pallet-ajuna-connectfour',
    'pallet-ajuna-rps',
    'pallet-ajuna-rpsonline',
    'pallet-ajuna-dotmog',
]